language: node_js
deploy:
  provider: npm
  email: csaba.tuncsik@gmail.com
  api_key:
    secure: LjQXNfIbWYY/73KRCLEJJUC8k1zZvUfxVfDLeRosJsa0rkEHzZRfHlN2DqpcDCO4OfhDhZglStClyOVOIDqTkPf00u1PjbeDR5qqOJBo+lLIE2FF7jEwrZeQS/5YDxlfou0HsV6tHY6Aet30pxcNe7OFV75BlDpB0xBYxyGn/nT0i7NRl23rl/kGpaIn/UnAuP9iZ0XOimfwHG1FnBMCs5/SAlcZzwA/DImqRR8Fl9ewVGm1ayCkjo/1P61/GS3qd4uHGSPDIzryS8cyIfTlO4q8Q0/zk0lMtgi8tAwrtjxkiOtCGpjqFD8K0dRH+H8URR7eDnURl5TjkNK/ZUCDO4Uq0YTQhBTjzDuUnZ3keWNZ6GGU2ArjNg9LsKFBv46KMv36aH1QxyYnSw1urtpaqcrFEQVDoWMJahvqZxgoiaZDzfOSqzFsgK5HtRIXcGLZepMfbOH9Rm25evYKMY/JFc4sdDNjRNYjgjlKSGLQMh9FgFGVcaFH2rKMAkQAW+wpwQAstvDxwWPizt8D9oJrZfeGXzK8NzrU/lb4iGqujkTXYw7H47zDAA7YkPFzdhmyVniPmXebOdY5LC8TeU7l745qRkPGG2Wnyg6Z9EywW4Qg/eTb9uRwV2b88Ebg2aR+ZDdLoG75fTKHb5De0GoDYUz+RPRDVH0Zx7Z/Tj8yCrE=
  on:
    tags: true
    all_branches: true
    repo: cstuncsik/gulp-json-minify
