language: node_js
node_js:
  - 18
cache:
  directories:
    - node_modules
before_script:
  - yarn install --ignore-engines
  - yarn lint
script:
  - yarn test
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    branch: master
notifications:
  email:
    recipients:
      - csaba.tuncsik@gmail.com
    on_success: always
    on_failure: always
